# Generated by Django 5.1.6 on 2025-03-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajaapertura',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='CERRADA', max_length=10),
        ),
        migrations.AlterField(
            model_name='cajaapertura',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
