# Generated by Django 5.1.6 on 2025-03-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0002_alter_cajaapertura_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajaapertura',
            name='estado',
        ),
        migrations.AddField(
            model_name='caja',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='CERRADA', max_length=10),
        ),
    ]
