# Generated by Django 5.1.6 on 2025-03-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='vendedor',
        ),
    ]
