# Generated by Django 5.1.6 on 2025-03-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_cambio_venta_descuento_general_venta_importe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cambio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento_general',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='venta',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
