# Generated by Django 5.1.6 on 2025-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_detalleventa_descuento_alter_venta_cambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
