# Generated by Django 5.1.6 on 2025-03-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_datosdomicilio_datosfiscales_usuario_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosDomicilio',
        ),
        migrations.DeleteModel(
            name='DatosFiscales',
        ),
    ]
