# Generated by Django 5.1.6 on 2025-03-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_delete_datosdomicilio_delete_datosfiscales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscontacto',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
