# Generated by Django 5.1.6 on 2025-03-04 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_delete_datosdomicilio_delete_datosfiscales'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('datos_contacto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.datoscontacto')),
                ('datos_domicilio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='negocio.datosdomicilio')),
            ],
        ),
    ]
