# Generated by Django 5.1.6 on 2025-03-11 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFiscales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='rfc',
        ),
        migrations.AddField(
            model_name='negocio',
            name='datos_fiscales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='negocio.datosfiscales'),
        ),
    ]
